project:
  type: website

website:
  title: "jhmartel.github.io"
  site-url: https://jhmartel.github.io/
  
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhmartel
      - icon: twitter
        href: https://twitter.com/_jhmlabs
#      - icon: rss
#        href: blog.xml
format:
  html:
    theme: cosmo
    css: styles.css



